print(2 > 6)
print(2 < 6 and 6 < 2)
print(False)
# print(false)
print(True)
print(True and False)
print(True or False)
print(False or False)
print(not True)
print(not not False)
print(not False and True)
print(not (False or True))
print(True and False and True)
print(True or (False and True))
# print((11/0 == 1) and False)
# print(False and (11/0 == 1))